name: PR Checks
on:
    pull_request:
        branches:
            - main
    # allows you to manually trigger this in GH actions
    workflow_dispatch:

env:
    CLIENT_ID: ${{ secrets.CLIENT_ID }}
    CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # Needed to get PR information, if any

jobs:
    Test_And_Audit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install Packages
              run: npm install

            - name: Audit
              run: npm audit --audit-level=high

            - name: Formatting
              run: npx prettier --check .

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test

            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
